config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.views import index

urlpatterns = [
    path('summernote/',include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("", index)
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like, post_delete

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("post_delete/<int:post_id>/", post_delete, name="post_delete"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup, profile, followers,following,follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
]

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    title = models.CharField("제목",max_length=50, default=None, null=True)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

    tags = models.ManyToManyField(
        "posts.HashTag", verbose_name='해시태그목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from posts.models import Comment, Post
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            # "user", 유저는 db에서 입력되어야함
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": "1",
                    "placeholder": "댓글달기...",
                    "style":"resize:none; border:none;"
                }
            )
        }

# 기존 포스트폼
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = [
#             "content",
#         ]
#         widgets = {
#             "content": forms.Textarea(
#                 attrs={
#                     "class": "form-control",
#                     "placeholder" : "내용을 작성해 주세요",
#                 }
#             )
#         }
        

# 섬머노트 포스트 폼 

class NoticeWriteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
    class Meta:
        model = Post
        fields = ['title','content']
        widgets = {
            'title' : forms.TextInput(
                attrs={"class":"form-control mb-2",
                    "placeholder":"제목을 작성해 주세요",
                    }),
            'content' : SummernoteWidget(
                attrs={'summernote': {"placeholder" : "내용을 작성해 주세요",
                                        # 'width': '100%', 'height': '500px' ,
                                    },
                        "class": "summernote form-control",
                }),
        }

posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, Comment, PostImage, HashTag
# from posts.forms import CommentForm, PostForm
from posts.forms import CommentForm, NoticeWriteForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse


# Create your views here.


def feeds(request):
    # if not request.user.is_authenticated:
    #     return redirect("/users/login/")
    print(request.user)
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, "posts/feeds.html", context)


@require_POST
def comment_add(request):
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.save()

        # url로 next 값을 전달 받으면, 댓글 작성 완료 후 전달받은 값으로 이동
        if request.GET.get("next"):
            url_next = request.GET.get("next")
        # next 값을 전달받지 않았다면, 피드 페이지의 글 위치로 이동
        else:
            url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"

        return HttpResponseRedirect(url_next)


@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
        url = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url)
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")


def post_add(request):
    if not request.user.is_authenticated:
        return redirect("/users/login/")
    
    if request.method == "POST":
        # content는 POSTFORM처리
        # form = PostForm(request.POST)
        form = NoticeWriteForm(request.POST)

        if form.is_valid():
            # user값은 request에서 가져와 자동 할당
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # post 생성 후 전송받은 이미지들을 순회하며 postimage 객체 생성
            for image_file in request.FILES.getlist("images"):
                # model으 imagefield에 바로 할당
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # tags에 전달된 문자열을 분리하여 해쉬태그 생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_names = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)

            # 생성 완료 후 피드페이지로 이동하여 생성된 post의 위치로 돌아옴
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # get에선 빈 form 출력
    else:
        form = NoticeWriteForm()

    context = {"form": form}
    return render(request, "posts/post_add.html", context)

def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    if post.user == request.user:
        post.delete()
        url = reverse("posts:feeds")
        return HttpResponseRedirect(url)
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")


def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags=tag)

    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, 'posts/tags.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "posts/post_detail.html", context)

# url에서 좋아요 처리할 Post의 id를 전달 받는다


def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아요를 누른 post 목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제
        user.like_posts.remove(post)

    # 존재하지 않는 다면, 좋아요 목록에 추가
    else:
        user.like_posts.add(post)

    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드 페이지에서 해당 Post 위치로 이동.
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)

templates/posts/feeds.html
{% extends "base_slider.html" %}
{% load custom_tags %}

{% block content %}
  <div id="feeds" class="post-container">
    {% comment %} 최신글을 위로가게 reversed {% endcomment %}
    {% for post in posts reversed %}
      {% url 'posts:feeds' as action_redirect_to %}
      {% include "posts/post.html" with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
    {% endfor %}
  </div>
{% endblock %}

templates/posts/post.html
<div class="container mt-5 mb-5 pt-5">
  <div class="card m-auto w-75">
    <article id="post-{{ post.id }}" class="post">
      <div class="card-header bg-white">
        <div class="row mt-1">
          <div class="col-6 text-start">
            <a href="{% url 'users:profile' user_id=post.user.id %}" class="text-decoration-none">
              {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}" class="rounded-circle" alt="" style="height:32px; width: 32px;">
              {% endif %}
              <span class="card-title fw-bold text-black">{{ post.user.username }}</span>
            </a>
          </div>
          <!-- {% comment %} follow unfollow {% endcomment %} -->
          <div class="col-6 text-end">
            {% if user.is_authenticated %}
              {% if user != post.user %}
                <form action="{% url 'users:follow' user_id=post.user.id %}?next={{action_redirect_url}}" method="POST">
                  {% csrf_token %}
                  {% if post.user in user.following.all %}
                    <button type="submit" class="btn btn-sm btn-outline-danger">
                      Unfollow
                    </button>
                  {% else %}
                    <button type="submit" class="btn btn-sm btn-outline-success">
                      Follow
                    </button>
                  {% endif %}
                </form>
              {% endif %}
            {% endif %}
          </div>
        </div>

        <div id="demo-{{post.id}}" class="carousel slide mt-1" data-bs-touch="false" data-bs-interval="false">
          <div class="carousel-indicators">
            {% for image in post.postimage_set.all %}
              <button data-bs-target="#demo-{{post.id}}" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></button>
            {% endfor %}
          </div>

          <div class="carousel-inner">
            {% for image in post.postimage_set.all %}
              <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                <img src="{{ image.photo.url }}" class="card-img " style="background-size: contain">
              </div>
            {% endfor %}
          </div>

          <button class="carousel-control-prev" data-bs-target="#demo-{{post.id}}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </button>
          <button class="carousel-control-next" data-bs-target="#demo-{{post.id}}" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
          </button>
        </div>

        <!-- {% comment %} 글내용 {% endcomment %} -->
        <div class="post-content">
          {{post.content|safe}}
          <!-- {% comment %} 작성일자 {% endcomment %} -->
          <div class="d-flex justify-content-end">
            <small class="ms-3">{{post.created}}</small>
          </div>

          <!-- {% comment %} 태그 {% endcomment %} -->
          <div class="d-inline-block d-flex justify-content-between">
            <div class="post-tags">
              {% for tag in post.tags.all %}
                <a href="{% url 'posts:tags' tag_name=tag.name %}" style="text-decoration:none;">#{{tag.name}}</a>
              {% endfor %}
            </div>
            <!-- 피드 삭제 버튼 -->
            <div class="post_delete">
              {% if user == post.user %}
                <form action="{% url 'posts:post_delete' post_id=post.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-outline-danger" style="--bs-btn-padding-y: .10rem; --bs-btn-padding-x: .3rem; --bs-btn-font-size: .60rem;">피드 삭제</button>
                </form>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="card-body">
        <!-- {% comment %} 좋아요 댓글 갯수 {% endcomment %} -->

        <div class="post-buttons">
          <div class="d-inline-block">
            <form action="{% url 'posts:post_like' post_id=post.id %}?next={{ action_redirect_url }}" method="POST">
              {% csrf_token %}
              {% if user.is_authenticated %}
                <button type="submit" class="btn" style="outline:none; scale:0.8">
                  {% if user in post.like_users.all %}
                    좋아요 취소({{ post.like_users.count }})
                  {% else %}
                    좋아요({{ post.like_users.count }})
                  {% endif %}
                </button>
              {% else %}
                좋아요({{ post.like_users.count }})
              {% endif %}
            </form>
          </div>
          <div class="d-inline-block">
            <span style="font-size:80%">
              댓글({{post.comment_set.count}})
            </span>
          </div>
        </div>

        <!-- {% comment %} 댓글 {% endcomment %} -->
        <div class="post-comments">
          <ul class="list-group">
            {% for comment in post.comment_set.all %}
              <li class="" style="list-style:none;">
                <b>{{comment.user.username}}</b>
                {{comment.content}}
                {% if user == comment.user %}
                  <div class="d-inline-block">
                    <form action="{% url 'posts:comment_delete' comment_id=comment.id %}" method="post">
                      {% csrf_token %}
                      {% comment %} <button type="submit" class="badge text-bg-primary">삭제</button> {% endcomment %}
                      <button type="submit" class="btn btn-sm btn-outline-danger" style="scale:0.8" >삭제</button>
                    </form>
                  </div>
                {% endif %}

              </li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <!-- {% comment %} 댓글입력창 {% endcomment %} -->
      {% if user.is_authenticated %}
        <div class="card-footer bg-white">
          <div class="post-comment-create">
            <form method="POST" class="" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
              {% csrf_token %}
              <div class="input-group">
                <input type="hidden" class="form-control" name="post" value="{{ post.id }}"/>
                {{ comment_form.content }}
                <button type="submit" class="btn btn-link" style="text-decoration:none; cursor: pointer;">게시</button>
              </div>
            </form>
          </div>
        </div>
      {% endif %}
    </article>
  </div>
</div>

templates/posts/post_add.html
{% extends 'base_nav.html' %}
{% block content %}

  <div class="mt-5 mb-5 ms-3 me-3 pt-5" id="post-add">
    <h3 class="fw-light">Post 작성</h3>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- content summernote -->
      <div class="summernote mt-2">
        <!-- <textarea id="summernote" name="editordata"></textarea> -->
        {{form}}
        </div>
        <!-- images -->
        <div>
          <label for="id_images">이미지</label>
          <div class="input-group">
            <input type="file" class="form-control" name="images" id="id_images" multiple="multiple"/>
          </div>
        </div>
        <!-- tags -->
        <div class="mt-2">
          <label for="id_tags">해시태그</label>
          <input type="text" class="form-control" id="id_tags" name="tags" placeholder="쉼표(,)로 구분하여 여러 태그 입력"/>
        </div>
        <div class="d-flex justify-content-center mt-2">
          <button type="submit" class="btn btn-outline-primary">게시</button>
        </div>
      </form>
    </div>
  {% endblock %}

templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}
	<div id="feeds" class="post-container">
		{% url 'posts:post_detail' post.id as action_redirect_to %}
		{% include "posts/post.html" with action_redirect_url=action_redirect_to %}
	</div>
{% endblock %}

templates/posts/tags.html
{% extends "base_nav.html" %}

{% block content %}
  <div id="tags" class="mt-5 pt-5">
    <header class="tags-header ms-2 me-2">
      <h2 class="fw-light fs-3">#{{tag_name}}</h2>
      <div class="fw-light">게시물
        {{posts.count}}</div>
    </header>
    <div class="post-grid-container">
      <div class="row text-center text-lg-start ms-1 me-1">
        {% for post in posts %}
          {% if post.postimage_set.first and post.postimage_set.first.photo %}
            <div class="col-lg-3 col-md-4 col-6 mb-2" style="width:360px;
				height:270px;
				overflow:hidden;
				margin:0 auto;">
              <a href="{% url 'posts:post_detail' post_id=post.id %}" class="d-block mb-4 h-100">
                <img src="{{post.postimage_set.first.photo.url}}" alt="" srcset="" class="img-fluid img-thumbnail" style="width:100%;
			  height:100%;
			  object-fit:cover;">
              </a>
            </div>
          {% endif %}
          {%empty%}
          <p>검색된 게시물이 없습니다.</p>
        {% endfor %}
      </div>
    </div>

  {% endblock %}