config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.views import index

urlpatterns = [
    path('summernote/',include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("", index)
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like, post_delete

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("post_delete/<int:post_id>/", post_delete, name="post_delete"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup, profile, followers,following,follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
]

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    title = models.CharField("제목",max_length=50, default=None, null=True)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

    tags = models.ManyToManyField(
        "posts.HashTag", verbose_name='해시태그목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>

    <!-- include libraries(jQuery, bootstrap) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>

    <!-- include summernote css/js-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Pystagram</title>
    {% block head %}{% endblock %}
  </head>

  <body>
    {% block base_content %}{% endblock %}
  </body>

</html>

templates/base.html
{% extends "_base.html" %}
{% block base_content %} 
    {% block content %}
    {% endblock %}
{% endblock %}

templates/base_nav.html
{% extends "_base.html" %}

{% block base_content %}
  {% include "nav.html" %}
  {% block content %}{% endblock %}
{% endblock %}

templates/base_profile.html
{% extends "base_nav.html" %} {% block content %}
<div class="ms-2" id="profile">
  <div class="info d-flex mt-5 mb-3 pt-5 pb-4 border-1 border-bottom border-bg-secondary">
    {% if user.profile_image %}
    <img
      src="{{user.profile_image.url}}"
      class="rounded-circle"
      alt=""
      style="height: 150px; width: 150px" />
    {% endif %}

    <div class="info-texts mt-4 ms-3">
      <h1 class="fw-normal">{{user.username}}</h1>
      <div class="counts">
        <dl class="d-flex">
          <dt class="me-1 fw-light">Posts</dt>
          <dd class="me-3">
            <a
              href="{% url 'users:profile' user_id=user.id %}"
              class="fw-bold text-black"
              style="text-decoration: none">
              {{user.post_set.count}}</a
            >
          </dd>
          <dt class="me-1 fw-light">Followers</dt>
          <dd class="me-3">
            <a
              href="{% url 'users:followers' user_id=user.id %}"
              class="fw-bold text-black"
              style="text-decoration: none">
              {{user.followers.count}}</a
            >
          </dd>
          <dt class="me-1 fw-light">Following</dt>
          <dd>
            <a
              href="{% url 'users:following' user_id=user.id %}"
              class="fw-bold text-black"
              style="text-decoration: none">
              {{user.following.count}}</a
            >
          </dd>
        </dl>
      </div>
      <p class="fw-light">{{user.short_description}}</p>
    </div>
  </div>
  {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

templates/base_slider.html
{% extends "_base.html" %}
{% load static %}

{% comment %} 이미지 슬라이드 기능은 일단 유지 {% endcomment %}
{% block head %}
  <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
  <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
  {% include "nav.html" %}
  {% block content %}{% endblock %}
  <script>
    const elms = document.getElementsByClassName('splide');
    for (let i = 0; i < elms.length; i++) {
      new Splide(elms[i]).mount();
    }
  </script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="ko">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<h1>pystagram</h1>
	</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-sm bg-body-tertiary fixed-top border-1 border-bottom border-bg-secondary">
  <div class="container-fluid">
    <h1>
      <a class="navbar-brand fw-bold ms-2" href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-2" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'posts:post_add' %}" class="nav-link text-primary">Add Post</a>
          </li>
          <li>
            <a href="{% url 'users:logout' %}" class="nav-link text-primary">Logout</a>
          </li>
        {% else %}
          <a href="{% url 'users:login' %}" class="nav-link text-primary">Login</a>
        </li>
      {% endif %}
    </li>
  </ul>
</div>
</div>
</nav>