config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.views import index

urlpatterns = [
    path('summernote/',include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("", index)
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import feeds, comment_add, comment_delete, post_add, tags, post_detail, post_like, post_delete

app_name = "posts"
urlpatterns = [
    path("feeds/", feeds, name="feeds"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("post_delete/<int:post_id>/", post_delete, name="post_delete"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup, profile, followers,following,follow

app_name = "users"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", signup, name="signup"),
    path("<int:user_id>/profile/", profile, name="profile"),
    path("<int:user_id>/followers/", followers, name="followers"),
    path("<int:user_id>/following/", following, name="following"),
    path("<int:user_id>/follow/", follow, name="follow"),
]

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    title = models.CharField("제목",max_length=50, default=None, null=True)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

    tags = models.ManyToManyField(
        "posts.HashTag", verbose_name='해시태그목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE
    )
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    profile_image = models.ImageField(
        "프로필 이미지", upload_to="users/profile", blank=True)
    short_description = models.TextField('소개글', blank=True)

    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name="좋아요 누른 Post 목록",
        related_name="like_users",
        blank=True,
    )
    following = models.ManyToManyField(
        "self",
        verbose_name="팔로우 중인 사람들",
        related_name="followers",
        symmetrical=False,
        through="users.Relationship"
    )
    def __str__(self):
        return self.username

class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우를 요청한 사용자",
        related_name="following_relationships",
        on_delete=models.CASCADE
    )
    to_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청의 대상",
        related_name="follower_relationships",
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"관계 ({self.from_user}->{self.to_user})"

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import User


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
        
    username = forms.CharField(
        label='사용자 이름',
        min_length=3,
        widget=forms.TextInput(
            attrs={"class":"form-control",
                    "placeholder": "사용자명 (3자리 이상)",
                    'autocomplete': 'off',
                    })
    )
    password = forms.CharField(
        label='비밀번호',
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"class":"form-control",
                    "placeholder": "비밀번호 (4자리 이상)", 
                    'autocomplete': 'asdadasdasd',
                    })
    )


class SignupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""
    
    username = forms.CharField(
        label='사용자 이름',
        min_length=3,
        widget=forms.TextInput(
            attrs={"class":"form-control",
                    "placeholder": "사용자명 (3자리 이상)",
                    'autocomplete': 'off',
                    })
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={"class":"form-control",
                    "placeholder": "비밀번호 (4자리 이상)", 
                    'autocomplete': 'asdadasdasd',
                    }))
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={"class":"form-control",
                    "placeholder": "비밀번호 (4자리 이상)", 
                    'autocomplete': 'asdadasdasd',
                    }))
    profile_image = forms.ImageField(
        label='프로필 이미지',
        widget=forms.FileInput(
            attrs={"class":"form-control"}
        )
    )
    short_description = forms.CharField(
        label='자기소개',
        widget=forms.TextInput(
            attrs={"class":"form-control",
                    "placeholder": "간단 소개",
                    'autocomplete': 'off',
                    })
    )

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중입니다.")
        return username

    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            self.add_error("password2", "비밀번호가 일치하지 않습니다.")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]
        user = User.objects.create_user(
            username=username,
            password=password1,
            profile_image=profile_image,
            short_description=short_description,
        )
        return user

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import LoginForm, SignupForm
from users.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.


def login_view(request):
    if request.user.is_authenticated:
        return redirect("posts:feeds")

    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("posts:feeds")
            else:
                # print("로그인에 실패했습니다.")
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다.")
        context = {"form": form}
        return render(request, "users/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form, }
        return render(request, "users/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("users:login")


def signup(request):
    # post 요청시 form이 유효하다면 최종적으로 redirect
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/posts/feeds/")
        
    # get요청시 빈 form    
    else:
        form = SignupForm()

    # post 요청 form이 유효하지 않거나, get으로 빈form이 생성되면 에러를 포함한 form이 출력
    context = {"form": form}
    return render(request, "users/signup.html", context)


def profile(request,user_id):
    print(request.user)
    user = get_object_or_404(User, id=user_id)
    context = {
        "user" :user,
    }
    return render(request,"users/profile.html",context)

def followers(request,user_id):
    user = get_object_or_404(User,id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request,"users/followers.html",context)

def following(request,user_id):
    user = get_object_or_404(User,id=user_id)
    relationships = user.following_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request,"users/following.html",context)

def follow(request,user_id):
    user = request.user
    target_user = get_object_or_404(User,id=user_id)
    
    if target_user in user.following.all():
        user.following.remove(target_user)
        
    else:
        user.following.add(target_user)
        
    url_next = request.GET.get("next") or reverse("user:profile", args=[user.id])
    return HttpResponseRedirect(url_next)

templates/users/followers.html
{% extends "base_profile.html" %}
{% block bottom_data %}
<div class="relationships">
  <h5 class="fw-semibold">Followers</h5>
  {% for relationship in relationships %}
  <div class="relationship mb-1 border-1 pb-1 border-bottom border-bg-secondary d-flex">
    <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
      {% if relationship.from_user.profile_image %}
      <img src="{{ relationship.from_user.profile_image.url }}" alt="" class="rounded-circle"
        style="height: 50px; width: 50px" />
      {% endif %}
      <div class="row ps-1 relationship-info">
        <a class="fw-medium text-black" href="{% url 'users:profile' user_id=relationship.from_user.id %}"
          style="text-decoration: none">
          {{ relationship.from_user.username }}
        </a>
        <a class="fw-medium text-black-50" href="{% url 'users:profile' user_id=relationship.from_user.id %}"
          style="text-decoration: none; font-size: 11px">
          {{ relationship.created|date:"y.m.d" }}
        </a>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/users/following.html
{% extends "base_profile.html" %}
{% block bottom_data %}
  <div class="relationships">
    <h5 class="fw-semibold">Following</h3>
    {% for relationship in relationships %}
      <div class="relationship mb-1 border-1 pb-1 border-bottom border-bg-secondary d-flex">
        <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
          {% if relationship.to_user.profile_image %}
            <img src="{{ relationship.to_user.profile_image.url }}" alt="" class="rounded-circle" style="height: 50px; width: 50px"/>
          {% endif %}

          <div class="row ps-1 relationship-info">
            <a class="fw-medium text-black" href="{% url 'users:profile' user_id=relationship.to_user.id %}" style="text-decoration: none">
              {{ relationship.to_user.username }}
            </a>
            <a class="fw-medium text-black-50" href="{% url 'users:profile' user_id=relationship.to_user.id %}" style="text-decoration: none; font-size: 11px">
              {{ relationship.created|date:"y.m.d" }}
            </a>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}

  <div class="d-flex" id="login" style="height: 100vh;">
    <div class="m-auto">
      <form class="card text-center" action="" method="post" style="width: 28rem;">
        <div class="card-body mb-4">
          <h1 class="fw-bold my-5">
            <a class="text-black text-decoration-none" href="{% url 'posts:feeds' %}">Pystagram</a>
          </h1>

          {% csrf_token %}
          <div class="row col-auto text-start mx-4">
            {{form.as_p}}
            <div class="row col-auto w-100 my-1 ms-0">
              <button type="submit" class="btn btn-primary">로그인</button>
            </div>
          </div>
          <a href=" {% url 'users:signup' %}" class="fs-6 text-black-50 text-decoration-none mt-1">회원가입 페이지로 이동</a>
        </div>
      </form>
    </div>
  </div>

  <!-- justify-content-center align-items-center h-100 mt-5 pt-5 -->

  {% endblock%}

templates/users/profile.html
{% extends "base_profile.html" %}

{% block bottom_data%}
  <div class="post-grid-container">
    <div class="row text-center text-lg-start ms-1 me-1">
      {% for post in user.post_set.all reversed %}
        {% if post.postimage_set.first and post.postimage_set.first.photo %}
          <div class="col-lg-3 col-md-4 col-6 mb-2" style="
          width:360px;
          height:270px;
          overflow:hidden;
          margin:0 auto;">
            <a href="{% url 'posts:post_detail' post_id=post.id %}" class="d-block mb-4 h-100">
              <img src="{{ post.postimage_set.first.photo.url }}" alt="" srcset="" class="img-fluid img-thumbnail" style="width:100%;
          height:100%;
          object-fit:cover;">
            </a>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
  <div class="d-flex" id="signup" style="height: 100vh;">
    <div class="m-auto">
      <form class="card text-center" style="width: 28rem;" action="" method="post" enctype="multipart/form-data">
        <div class="card-body mb-4">
          <h1 class="fw-bold my-5">
            <a class="text-black text-decoration-none" href="{% url 'posts:feeds' %}">Pystagram</a>
          </h1>
          {% csrf_token %}
          <div class="row col-auto text-start mx-4">
            {{form.as_p}}
            <div class="row col-auto w-100 my-1 ms-0">
              <button type="submit" class="btn btn-primary">회원가입</button>
            </div>
          </div>
          <a href="{% url 'users:login' %}" class="fs-6 text-black-50 text-decoration-none">로그인 페이지로 이동</a>
        </div>
      </form>
    </div>
  </div>

{% endblock %}